version: '3.8'
services:
  db:
    image: postgres:13
    env_file:
      - ./db.env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3001:80"
    depends_on:
      - backend
volumes:
  db-data:
